### PR TITLE
Cleanup manifest

### PR DESCRIPTION
**Pull request by JarlPenguin**
Signed-off-by: JarlPenguin <jarlpenguin@outlook.com>

### CODE REVIEW

**Comment by JarlPenguin** [comment]
fixed little typo

**Comment by JarlPenguin** [comment]
did some tidying up

**Review by johnlaff — APPROVED** [review]
Thanks for the suggestion, I'll do the merge here! Organization really matters!

**Comment by JarlPenguin** [comment]
cleanup 1/2

> Thanks for the suggestion, I'll do the merge here! Organization really matters!

No problem

**Comment by JarlPenguin** [comment]
Cleanup done. Merging

**Pull request merged**
